version: '3.8'

services:
    memoires-db:
        image: bitnami/postgresql:14.3.0
        container_name: memoires-db
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USERNAME: ${POSTGRES_USERNAME}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - memoires-postgres:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432

    memoires-api:
        build: .
        image: memoires
        container_name: memoires-api
        environment:
            POSTGRES_SERVER: memoires-db
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USERNAME: ${POSTGRES_USERNAME}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}
        ports:
            - 8000:8000
        depends_on:
            - memoires-db
        volumes:
            - ./app:/src/app

volumes:
    memoires-postgres:
