FROM python:3.10.8

ENV POETRY_VERSION=1.2.2
RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /src

ENV PYTHONPATH="$PYTHONPATH:/src/app"
COPY poetry.lock pyproject.toml /src/

RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction
COPY app /src/app/
COPY README.md /src
COPY CHANGELOG.md /src

RUN env | grep BUILD_ > /src/build_envs.txt; exit 0

ENTRYPOINT ["ptw", "-c", "/src"]
