version: '3.8'

services:
    memoires-db-test:
        image: bitnami/postgresql:14.3.0
        environment:
            POSTGRES_PASSWORD: memoires
            POSTGRES_USERNAME: memoires
            POSTGRES_DB: memoires
        networks:
            - memoires-test

    memoires-api-test:
        build:
            context: .
            dockerfile: Dockerfile-pytest
        environment:
            POSTGRES_SERVER: memoires-db-test
            POSTGRES_PASSWORD: memoires
            POSTGRES_USERNAME: memoires
            POSTGRES_DB: memoires
            POSTGRES_PORT: 5432
            MINIO_ADDR: memoires-minio-test
            MINIO_PORT: 9000
            MINIO_ACCESS_KEY: memoires
            MINIO_ACCESS_PASSWORD: memoires
            MINIO_SSL: false
        networks:
            - memoires-test
        depends_on:
            - memoires-db-test
            - memoires-minio-test
        volumes:
            - ./app:/src/app

    memoires-minio-test:
        image: bitnami/minio:latest
        networks:
            - memoires-test
        environment:
            - MINIO_ROOT_USER=memoires
            - MINIO_ROOT_PASSWORD=memoires
            - MINIO_DEFAULT_BUCKETS=memoires
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

networks:
    memoires-test:
