version: '3.8'

services:
    memoires-db:
        image: bitnami/postgresql:14.3.0
#        container_name: memoires-db
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USERNAME: ${POSTGRES_USERNAME}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - memoires-postgres:/var/lib/postgresql/data
        networks:
            - memoires
        ports:
            - ${POSTGRES_PORT}:5432

    memoires-api:
        build: .
#        image: registry.digitalocean.com/evanjt/memoires-api
        container_name: memoires-api
        environment:
            POSTGRES_SERVER: memoires-db
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USERNAME: ${POSTGRES_USERNAME}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}
            MINIO_ADDR: minio
            MINIO_PORT: 9000
            MINIO_ACCESS_KEY: minio-root-user
            MINIO_ACCESS_PASSWORD: minio-root-password
            MINIO_SSL: false
        networks:
            - memoires
        ports:
            - 8000:8000
        depends_on:
            - memoires-db
        volumes:
            - ./app:/src/app

    minio:
        image: bitnami/minio:latest
        volumes:
            - memoires-minio:/data
            #- ./data:/data
        networks:
            - memoires
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=minio-root-user
            - MINIO_ROOT_PASSWORD=minio-root-password
            - MINIO_DEFAULT_BUCKETS=memoires

volumes:
    memoires-postgres:
    memoires-minio:

networks:
    memoires:
